- hosts: all
  tasks:

      - block:
          - name: Install missing updates.
            win_updates: category_names=['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups']
            reboot: yes

